name: Compile PDFs

on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Compile
      run: make


    - name: Upload generated PDF as artifact
      uses: actions/upload-artifact@v4
      with:
        name: resume-pdf
        path: |
          ./*.pdf
